/*
 * Copyright 2026 MobileByteLabs
 *
 * Documentation surface for the multi-dim-3d sample. Demonstrates how a
 * consumer reads the BuildKonfig + (v2.6 Phase 3) AnalyticsTags fields generated
 * by the plugin. The active variant resolves to one of:
 *   devPhoneFree, devPhonePaid, devTabletFree, devTabletPaid, prdPhonePaid, prdTabletPaid
 * (Ordering is dimension-priority-based; see FlavorVariantResolver.)
 *
 * **Note:** this file is a documentation example — it's compiled by the plugin's
 * snapshot tests / TestKit fixtures, not by `:samples:multi-dim-3d:compileKotlinDesktop`.
 * The active variant's generated source sets land in `<target>Main`, not
 * `commonMain`, so `commonMain/kotlin/Sample.kt` cannot resolve them at compile
 * time. Move this file into `src/desktopMain/kotlin/` (or any platform's main
 * source set) to compile end-to-end in your own fork.
 *
 * Switch active variant via -PkmpFlavor=devPhoneFree (or any of the 6 variants).
 */

@file:Suppress("unused")

package com.example.multidim3d

import com.example.multidim3d.BuildKonfig

/**
 * Returns a description of the active variant's flavor combination.
 *
 * Demonstrates reading the three dimension constants generated by BuildKonfig:
 *   - IS_<TIER> flag (IS_FREE / IS_PAID)
 *   - IS_<ENV> flag (IS_DEV / IS_PRD)
 *   - IS_<FORM> flag (IS_PHONE / IS_TABLET)
 *
 * Plus custom buildConfigFields from each dimension's flavors.
 */
fun describeActiveVariant(): String {
    val tier = if (BuildKonfig.IS_PREMIUM) "paid" else "free"
    val env = if (BuildKonfig.API_BASE_URL.contains("dev")) "dev" else "prd"
    val form = if (BuildKonfig.IS_TABLET) "tablet" else "phone"
    return "active variant: $tier × $env × $form (maxItems=${BuildKonfig.MAX_ITEMS}, " +
        "apiBaseUrl=${BuildKonfig.API_BASE_URL})"
}

/**
 * v2.6 Phase 3 — read the auto-generated `AnalyticsTags` object.
 *
 * Proves the analytics codegen wired the active variant's `AnalyticsTags.kt` via
 * PerVariantAnalyticsTagConfigurator (active variant routes into each target's
 * `main` compilation defaultSourceSet — the same path BuildKonfig uses).
 */
fun describeAnalyticsTags(): String =
    "variant=${AnalyticsTags.VARIANT_NAME}, " +
        "buildType=${AnalyticsTags.BUILD_TYPE}, " +
        "environment=${AnalyticsTags.ENVIRONMENT}, " +
        "tier=${AnalyticsTags.TIER}"
