/*
 * Copyright 2026 MobileByteLabs
 *
 * Sample consumer code that reads the BuildKonfig fields generated by the v2.5
 * multi-dim-3d sample. Proves that 3-dimension cross-product variants produce
 * a working BuildKonfig surface readable from commonMain.
 *
 * The active variant resolves to one of:
 *   freeDevPhone, freeDevTablet, paidDevPhone, paidDevTablet, paidPrdPhone, paidPrdTablet
 *
 * Switch active variant via -PkmpFlavor=freeDevPhone (or any of the 6 variants).
 */

@file:Suppress("unused")

package com.example.multidim3d

import com.example.multidim3d.BuildKonfig

/**
 * Returns a description of the active variant's flavor combination.
 *
 * Demonstrates reading the three dimension constants generated by BuildKonfig:
 *   - IS_<TIER> flag (IS_FREE / IS_PAID)
 *   - IS_<ENV> flag (IS_DEV / IS_PRD)
 *   - IS_<FORM> flag (IS_PHONE / IS_TABLET)
 *
 * Plus custom buildConfigFields from each dimension's flavors.
 */
fun describeActiveVariant(): String {
    val tier = if (BuildKonfig.IS_PREMIUM) "paid" else "free"
    val env = if (BuildKonfig.API_BASE_URL.contains("dev")) "dev" else "prd"
    val form = if (BuildKonfig.IS_TABLET) "tablet" else "phone"
    return "active variant: $tier × $env × $form (maxItems=${BuildKonfig.MAX_ITEMS}, " +
        "apiBaseUrl=${BuildKonfig.API_BASE_URL})"
}
