// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
// Uses reflection to read BuildConfig so this compiles in both
// `com.android.application` modules (full BuildConfig present) and
// `com.android.library` modules (sparse or no BuildConfig).
package com.example.snapshot

public actual object KmpFlavorsRuntime {
    private fun readStringField(className: String, fieldName: String): String? = try {
        Class.forName(className).getField(fieldName).get(null) as? String
    } catch (_: Throwable) {
        null
    }

    private fun readBooleanField(className: String, fieldName: String): Boolean? = try {
        val f = Class.forName(className).getField(fieldName)
        (f.get(null) as? Boolean)
    } catch (_: Throwable) {
        null
    }

    private val buildConfigClass: String = "com.example.snapshot.BuildConfig"

    public actual val flavorName: String =
        readStringField(buildConfigClass, "FLAVOR") ?: ""
    public actual val buildTypeName: String =
        readStringField(buildConfigClass, "BUILD_TYPE") ?: ""
    public actual val bundleId: String =
        readStringField(buildConfigClass, "APPLICATION_ID") ?: ""
    public actual val applicationId: String = bundleId
    public actual val appDisplayName: String = ""
    public actual val appVersion: String =
        readStringField(buildConfigClass, "VERSION_NAME") ?: ""
    public actual val isDebug: Boolean =
        readBooleanField(buildConfigClass, "DEBUG") ?: false
    public actual val isDemo: Boolean =
        readBooleanField(buildConfigClass, "IS_DEMO") ?: (flavorName == "demo")
    public actual fun get(key: String): String? = when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "applicationId" -> applicationId
        "appDisplayName" -> appDisplayName
        "appVersion" -> appVersion
        "isDebug" -> isDebug.toString()
        "isDemo" -> isDemo.toString()
        else -> null
    }
}
