// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package com.example.snapshot

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_FLAVOR_NAME__: String

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_BUILD_TYPE_NAME__: String

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_BUNDLE_ID__: String

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_APP_DISPLAY_NAME__: String

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_APP_VERSION__: String

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_IS_DEBUG__: Boolean

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_IS_DEMO__: Boolean

public actual object KmpFlavorsRuntime {
    public actual val flavorName: String = __KMPF_FLAVOR_NAME__
    public actual val buildTypeName: String = __KMPF_BUILD_TYPE_NAME__
    public actual val bundleId: String = __KMPF_BUNDLE_ID__
    public actual val applicationId: String = bundleId
    public actual val appDisplayName: String = __KMPF_APP_DISPLAY_NAME__
    public actual val appVersion: String = __KMPF_APP_VERSION__
    public actual val isDebug: Boolean = __KMPF_IS_DEBUG__
    public actual val isDemo: Boolean = __KMPF_IS_DEMO__
    public actual fun get(key: String): String? = when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "appVersion" -> appVersion
        else -> null
    }
}
