/*
 * Copyright 2026 Anthropic, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.anthropic.kmpflavors.tasks

import com.anthropic.kmpflavors.BuildConfigField
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Task that generates a Kotlin BuildConfig object with flavor information.
 *
 * This task is cacheable, meaning Gradle can reuse outputs from previous builds
 * when the inputs haven't changed.
 *
 * Generated file structure:
 * ```kotlin
 * package com.example.app
 *
 * object FlavorConfig {
 *     const val VARIANT_NAME: String = "freeDev"
 *     const val IS_FREE: Boolean = true
 *     const val IS_PAID: Boolean = false
 *     const val IS_DEV: Boolean = true
 *     const val IS_PROD: Boolean = false
 *     // Custom fields from buildConfigField()
 *     const val BASE_URL: String = "https://dev-api.example.com"
 * }
 * ```
 */
@CacheableTask
abstract class GenerateBuildConfigTask : DefaultTask() {

    /**
     * The package name for the generated file.
     * Example: "com.example.app"
     */
    @get:Input
    abstract val packageName: Property<String>

    /**
     * The class name for the generated object.
     * Default: "FlavorConfig"
     */
    @get:Input
    abstract val className: Property<String>

    /**
     * The active variant name.
     * Example: "freeDev"
     */
    @get:Input
    abstract val variantName: Property<String>

    /**
     * Set of all flavor names (for generating IS_<FLAVOR> constants).
     * Example: ["free", "paid", "dev", "prod"]
     */
    @get:Input
    abstract val allFlavorNames: SetProperty<String>

    /**
     * Set of active flavor names (IS_<FLAVOR> = true).
     * Example: ["free", "dev"]
     */
    @get:Input
    abstract val activeFlavorNames: SetProperty<String>

    /**
     * Custom build config fields merged from active flavors.
     * Key: field name, Value: BuildConfigField(type, name, value)
     */
    @get:Input
    abstract val buildConfigFields: MapProperty<String, BuildConfigField>

    /**
     * Output directory for generated files.
     * Default: build/generated/kmpFlavors/commonMain/kotlin
     */
    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    init {
        group = "kmp flavors"
        description = "Generates BuildConfig Kotlin object with flavor information"
    }

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val clsName = className.get()
        val variant = variantName.get()
        val allFlavors = allFlavorNames.get()
        val activeFlavors = activeFlavorNames.get()
        val fields = buildConfigFields.get()

        // Create package directory
        val packageDir = pkg.replace('.', File.separatorChar)
        val outputDir = outputDirectory.get().asFile
        val targetDir = File(outputDir, packageDir)
        targetDir.mkdirs()

        // Generate the Kotlin file
        val outputFile = File(targetDir, "$clsName.kt")
        val content = buildString {
            appendLine("/*")
            appendLine(" * Generated by KMP Product Flavors Plugin")
            appendLine(" * DO NOT EDIT - This file is automatically generated")
            appendLine(" */")
            appendLine()
            appendLine("package $pkg")
            appendLine()
            appendLine("/**")
            appendLine(" * Build configuration for the active flavor variant.")
            appendLine(" *")
            appendLine(" * Active variant: $variant")
            appendLine(" * Active flavors: ${activeFlavors.joinToString(", ")}")
            appendLine(" */")
            appendLine("object $clsName {")
            appendLine()

            // Variant name
            appendLine("    /** The active variant name */")
            appendLine("    const val VARIANT_NAME: String = \"$variant\"")
            appendLine()

            // IS_<FLAVOR> constants
            if (allFlavors.isNotEmpty()) {
                appendLine("    // Flavor flags")
                for (flavor in allFlavors.sorted()) {
                    val isActive = flavor in activeFlavors
                    val constName = "IS_${flavor.uppercase()}"
                    appendLine("    const val $constName: Boolean = $isActive")
                }
                appendLine()
            }

            // Custom build config fields
            if (fields.isNotEmpty()) {
                appendLine("    // Custom build config fields")
                for ((_, field) in fields.entries.sortedBy { it.key }) {
                    val typeStr = field.type
                    val nameStr = field.name
                    val valueStr = field.value
                    appendLine("    const val $nameStr: $typeStr = $valueStr")
                }
            }

            appendLine("}")
            appendLine()
        }

        outputFile.writeText(content)
        logger.lifecycle("[KMP Flavors] Generated $outputFile")
    }
}
