/*
 * Copyright 2026 MobileByteLabs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.mobilebytelabs.kmpflavors

import org.gradle.api.provider.Property
import javax.inject.Inject

/**
 * How the generated `Package.swift` should reference the per-flavor `XCFramework`.
 *
 * - [LOCAL]: write a `binaryTarget(name: "...", path: "<path-to-xcframework>")`. Suitable for
 *   local development against an XCFramework already built into `build/`.
 * - [REMOTE]: write `binaryTarget(name: "...", url: "...", checksum: "...")`. The URL is
 *   resolved by interpolating the active variant into [SpmConfig.binaryUrlTemplate]. The
 *   checksum is read from a sibling `.checksum` file or computed at task time depending on
 *   [SpmConfig.checksumStrategy].
 */
enum class SpmDistribution { LOCAL, REMOTE }

/**
 * How the SPM manifest task should obtain the SHA256 checksum for a [SpmDistribution.REMOTE]
 * binary target.
 *
 * - [AUTO]: try to read `<xcframeworkPath>.checksum` if present; otherwise compute it
 *   on-the-fly from the local XCFramework if available; otherwise leave a `<TODO>` placeholder
 *   that fails the manifest validation step in CI.
 * - [REQUIRE_FILE]: only use a sidecar `<xcframeworkPath>.checksum` file. Fail the task
 *   loudly if missing.
 * - [SKIP]: emit a checksum-less manifest. Useful for samples / CI smoke tests where the
 *   binary is not actually fetched.
 */
enum class SpmChecksumStrategy { AUTO, REQUIRE_FILE, SKIP }

/**
 * Configuration for the per-flavor `Package.swift` generator.
 *
 * Decision D6 (per-flavor manifest): one `Package.swift` per active flavor variant. A unified
 * manifest with conditional product targets is **not** generated by v1.1.0 — consumers can
 * compose multiple per-flavor manifests if needed. Unified manifest is roadmapped for v1.3.0+.
 *
 * Example (local-development XCFramework):
 * ```kotlin
 * kmpFlavors {
 *     spm {
 *         generateManifest.set(true)
 *         xcframeworkName.set("Shared")
 *         distribution.set(SpmDistribution.LOCAL)
 *     }
 * }
 * ```
 *
 * Example (remote distribution):
 * ```kotlin
 * kmpFlavors {
 *     spm {
 *         generateManifest.set(true)
 *         xcframeworkName.set("Shared")
 *         distribution.set(SpmDistribution.REMOTE)
 *         binaryUrlTemplate.set("https://cdn.example.com/{flavor}/{version}/Shared.xcframework.zip")
 *         checksumStrategy.set(SpmChecksumStrategy.AUTO)
 *     }
 * }
 * ```
 */
abstract class SpmConfig @Inject constructor() {

    /**
     * Master switch — when false (the default), no SPM manifest task is registered.
     */
    abstract val generateManifest: Property<Boolean>

    /**
     * Logical name of the XCFramework as it will be exposed to Swift consumers (i.e. the
     * `name:` of the `binaryTarget` in `Package.swift`). Should match the XCFramework's
     * own logical name produced by your KMP build (`framework { baseName.set("...") }`).
     *
     * Convention: `"Shared"`.
     */
    abstract val xcframeworkName: Property<String>

    /**
     * One of [SpmDistribution.LOCAL] (path-based) or [SpmDistribution.REMOTE] (URL+checksum).
     *
     * Convention: [SpmDistribution.LOCAL].
     */
    abstract val distribution: Property<SpmDistribution>

    /**
     * URL template for [SpmDistribution.REMOTE] — supports the placeholders `{flavor}`,
     * `{variant}`, and `{version}` which are interpolated at task time. The variant
     * placeholder maps to the full active variant name (e.g. `freeAdvancedProdRelease`).
     * Ignored when [distribution] is [SpmDistribution.LOCAL].
     */
    abstract val binaryUrlTemplate: Property<String>

    /**
     * Local path (relative to the module's `build/` directory) to the per-variant
     * XCFramework. Defaults to `XCFrameworks/<variant>/<xcframeworkName>.xcframework` when
     * unset. Ignored when [distribution] is [SpmDistribution.REMOTE].
     */
    abstract val xcframeworkPath: Property<String>

    /**
     * Checksum strategy for [SpmDistribution.REMOTE]. See [SpmChecksumStrategy].
     *
     * Convention: [SpmChecksumStrategy.AUTO].
     */
    abstract val checksumStrategy: Property<SpmChecksumStrategy>

    init {
        generateManifest.convention(false)
        xcframeworkName.convention("Shared")
        distribution.convention(SpmDistribution.LOCAL)
        checksumStrategy.convention(SpmChecksumStrategy.AUTO)
    }
}
