/*
 * Copyright 2026 MobileByteLabs
 *
 * Example of accessing flavor configuration in common code.
 */

package com.example.sample.core

// The FlavorConfig is generated by the kmp-product-flavors plugin
// import com.example.sample.core.FlavorConfig

/**
 * Application configuration that uses flavor-specific values.
 */
object AppConfig {

    /**
     * Whether the app is running in demo mode.
     *
     * In a real project, this would use the generated FlavorConfig:
     * ```kotlin
     * val isDemoMode: Boolean = FlavorConfig.VARIANT_NAME == "demo"
     * ```
     */
    val isDemoMode: Boolean
        get() = true // Placeholder - use FlavorConfig.VARIANT_NAME in real code

    /**
     * The API base URL for the current flavor.
     *
     * In a real project:
     * ```kotlin
     * val apiUrl: String = FlavorConfig.API_URL
     * ```
     */
    val apiUrl: String
        get() = "https://demo-api.example.com" // Placeholder - use FlavorConfig.API_URL

    /**
     * Whether logging is enabled for the current flavor.
     *
     * In a real project:
     * ```kotlin
     * val loggingEnabled: Boolean = FlavorConfig.ENABLE_LOGGING
     * ```
     */
    val loggingEnabled: Boolean
        get() = true // Placeholder - use FlavorConfig.ENABLE_LOGGING
}
