/*
 * Copyright 2026 MobileByteLabs
 *
 * Sample consumer code that reads the rich BuildKonfig output generated by the
 * v2.5 buildkonfig-rich sample. Demonstrates each of the four DSL features.
 */

@file:Suppress("unused")

package com.example.buildkonfigrich

import com.example.buildkonfigrich.BuildKonfig

/** Demonstrate enum(dimension) — pattern-match on auto-generated sealed class. */
fun describeTier(): String = when (BuildKonfig.tier) {
    BuildKonfig.Tier.Free -> "Free tier — limited features"
    BuildKonfig.Tier.Paid -> "Paid tier — full features"
}

/** Demonstrate enum(dimension) for env — second dimension. */
fun describeEnv(): String = when (BuildKonfig.env) {
    BuildKonfig.Env.Dev -> "dev environment — local Supabase"
    BuildKonfig.Env.Prod -> "prod environment — production Supabase"
}

/** Demonstrate customField<List<String>> — typed list field. */
fun grantedScopes(): List<String> = BuildKonfig.scopes

/** Demonstrate secret(id) placeholder emission — value is "<unresolved:...>" in v2.5. */
fun apiKeyPlaceholder(): String = BuildKonfig.API_KEY
