/*
 * Copyright 2026 MobileByteLabs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.mobilebytelabs.kmpflavors.internal

import com.mobilebytelabs.kmpflavors.FeatureFlagsConfig
import com.mobilebytelabs.kmpflavors.FlavorVariant
import com.mobilebytelabs.kmpflavors.KmpFlavorExtension
import org.gradle.api.Project
import org.gradle.api.logging.Logger
import java.io.File

/**
 * v2.2 Phase 4B — feature-flag generator helpers (GrowthBook / Statsig / LaunchDarkly).
 *
 * For each platform whose `defaultPayload` is set, generates a per-variant
 * `FeatureFlags.kt` Kotlin object alongside the existing `BuildKonfig.kt`. The
 * generated object embeds the JSON payload as a `Map<String, String>` so the
 * consumer's flag-platform SDK can read variant-aware defaults at runtime.
 *
 * Output path: `build/generated/kmpFlavors/{variantName}/kotlin/{package}/FeatureFlags.kt`.
 *
 * Per-variant overrides: if a sibling file `flags/<platform>.<variantName>.json`
 * exists next to the base `defaultPayload`, its values override the base map for
 * that variant only.
 *
 * No-op when:
 *   - `featureFlags` block isn't configured.
 *   - All three platforms have `enabled=false` (default) AND no `defaultPayload`.
 *   - Matrix mode is off (no per-variant codegen target).
 *
 * Generated artefact lives under `build/generated/kmpFlavors/...` like other
 * codegen, so v2.1 Phase 4's `excludeGeneratedFromFormatters` helper already
 * excludes it from Spotless / Detekt scans.
 */
internal object FeatureFlagHelpers {

    fun configure(project: Project, extension: KmpFlavorExtension, allVariants: List<FlavorVariant>, matrixModeEnabled: Boolean, logger: Logger) {
        if (!matrixModeEnabled || allVariants.isEmpty()) return

        val featureFlags = extension.featureFlags
        val growthbookPayload = featureFlags.growthbook.defaultPayload.orNull?.asFile
        val statsigPayload = featureFlags.statsig.defaultPayload.orNull?.asFile
        val launchDarklyPayload = featureFlags.launchDarkly.defaultPayload.orNull?.asFile

        if (growthbookPayload == null && statsigPayload == null && launchDarklyPayload == null) {
            // Nothing configured — silent no-op.
            return
        }

        val packageName = extension.buildConfigPackage.orNull
        if (packageName.isNullOrBlank()) {
            logger.warn(
                "[KMP Flavors] Phase 4B — featureFlags configured but `buildConfigPackage` is unset. " +
                    "FeatureFlags.kt requires a package name to generate. Set " +
                    "`kmpFlavors.buildConfigPackage.set(\"com.example.app\")`.",
            )
            return
        }

        var generated = 0
        for (variant in allVariants) {
            val targetDir = File(
                project.layout.buildDirectory.get().asFile,
                "generated/kmpFlavors/${variant.name}/kotlin/${packageName.replace('.', File.separatorChar)}",
            )
            targetDir.mkdirs()
            val outputFile = File(targetDir, "FeatureFlags.kt")

            val sections = mutableListOf<String>()
            if (growthbookPayload != null) {
                sections += renderPlatformSection(
                    platformName = "growthbook",
                    basePayload = growthbookPayload,
                    variantName = variant.name,
                )
            }
            if (statsigPayload != null) {
                sections += renderPlatformSection(
                    platformName = "statsig",
                    basePayload = statsigPayload,
                    variantName = variant.name,
                )
            }
            if (launchDarklyPayload != null) {
                sections += renderPlatformSection(
                    platformName = "launchDarkly",
                    basePayload = launchDarklyPayload,
                    variantName = variant.name,
                )
            }

            val content = buildString {
                appendLine("/*")
                appendLine(" * Generated by KMP Product Flavors Plugin (v2.2 Phase 4B feature-flag helpers)")
                appendLine(" * DO NOT EDIT — overwritten on every configuration.")
                appendLine(" *")
                appendLine(" * Variant: ${variant.name}")
                appendLine(" */")
                appendLine()
                appendLine("package $packageName")
                appendLine()
                appendLine("/**")
                appendLine(" * Per-variant feature-flag defaults for variant '${variant.name}'.")
                appendLine(" *")
                appendLine(" * Read by the consumer's flag-platform SDK at app init time:")
                appendLine(" * ```kotlin")
                appendLine(" * GrowthBook.initialize(defaultPayload = FeatureFlags.growthbook)")
                appendLine(" * ```")
                appendLine(" *")
                appendLine(" * Values are strings — the SDK parses semantic types from the JSON shape.")
                appendLine(" */")
                appendLine("object FeatureFlags {")
                for (section in sections) {
                    append(section)
                }
                appendLine("}")
            }

            outputFile.writeText(content)
            generated += 1
        }

        if (generated > 0) {
            logger.lifecycle(
                "[KMP Flavors] Phase 4B — generated FeatureFlags.kt for $generated variant(s) " +
                    "(platforms: " + listOfNotNull(
                        if (growthbookPayload != null) "GrowthBook" else null,
                        if (statsigPayload != null) "Statsig" else null,
                        if (launchDarklyPayload != null) "LaunchDarkly" else null,
                    ).joinToString(", ") + ").",
            )
        }
    }

    /**
     * Render one platform's section inside the per-variant `FeatureFlags` Kotlin object.
     *
     * Reads `basePayload` (e.g. `flags/growthbook.json`). If a sibling
     * `flags/<platform>.<variantName>.json` exists, its values override the base for
     * this variant only.
     */
    private fun renderPlatformSection(platformName: String, basePayload: File, variantName: String): String {
        // Read base map.
        val baseEntries = parseJsonStringMap(basePayload)
        // Read variant override if present.
        val overrideFile = File(
            basePayload.parentFile,
            "${basePayload.nameWithoutExtension}.$variantName.json",
        )
        val overrideEntries = if (overrideFile.exists()) {
            parseJsonStringMap(overrideFile)
        } else {
            emptyMap()
        }
        // Merge — variant overrides win.
        val merged = (baseEntries + overrideEntries).toSortedMap()

        return buildString {
            appendLine("    /**")
            appendLine("     * $platformName defaults for variant '$variantName'.")
            appendLine("     * Base: ${basePayload.name}. Override: ${overrideFile.name} (${if (overrideFile.exists()) "present" else "absent"}).")
            appendLine("     */")
            append("    val ").append(platformName).append(": Map<String, String> = mapOf(")
            if (merged.isEmpty()) {
                appendLine(")")
            } else {
                appendLine()
                for ((key, value) in merged) {
                    append("        ").append(escapeKotlinString(key)).append(" to ").append(escapeKotlinString(value)).appendLine(",")
                }
                appendLine("    )")
            }
            appendLine()
        }
    }

    /**
     * Naïve JSON parser that handles a flat `{ "key": "value", ... }` shape. Sufficient
     * for v2.2 — consumers wanting nested JSON should pre-flatten or wait for v2.3's
     * full JSON parser. Returns the parsed map or empty on parse failure.
     */
    private fun parseJsonStringMap(file: File): Map<String, String> {
        if (!file.exists()) return emptyMap()
        val text = file.readText().trim()
        if (!text.startsWith("{") || !text.endsWith("}")) return emptyMap()
        val body = text.substring(1, text.length - 1).trim()
        if (body.isEmpty()) return emptyMap()
        val result = mutableMapOf<String, String>()
        // Split on top-level commas. Naïve — works for flat shape.
        var depth = 0
        var start = 0
        val pairs = mutableListOf<String>()
        for (i in body.indices) {
            val c = body[i]
            if (c == '{' || c == '[') depth += 1
            if (c == '}' || c == ']') depth -= 1
            if (c == ',' && depth == 0) {
                pairs += body.substring(start, i)
                start = i + 1
            }
        }
        pairs += body.substring(start)
        for (pair in pairs) {
            val colonIdx = pair.indexOf(':')
            if (colonIdx < 0) continue
            val rawKey = pair.substring(0, colonIdx).trim().removeSurrounding("\"")
            val rawValue = pair.substring(colonIdx + 1).trim().removeSurrounding("\"")
            result[rawKey] = rawValue
        }
        return result
    }

    private fun escapeKotlinString(s: String): String {
        val escaped = s.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }
}
