/*
 * Copyright 2026 MobileByteLabs
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

package com.mobilebytelabs.kmpflavors.internal

/**
 * Validator codes for the phase-dispatcher integrators (AGP / KMP / iOS / Desktop / Web).
 * Numerically continues the V01-V30 range owned by KmpFlavorPluginValidator.
 */
internal object FlavorValidationCodes {
    const val V31_PURE_AGP_NO_KMP_WIRING = "KMPF-V31"
    const val V32_PURE_AGP_NO_CODEGEN_CLAIM = "KMPF-V32"
    const val V33_BUNDLE_ID_SUFFIX_FORMAT = "KMPF-V33"
    const val V34_NO_BUNDLE_ID_SUFFIX_WARN = "KMPF-V34"
    const val V35_COMPOSE_NO_INTEGRATOR = "KMPF-V35"
    const val V36_WEB_NO_INTEGRATOR = "KMPF-V36"
    const val V37_RUNTIME_EXPECT_AND_ACTUAL = "KMPF-V37"
    const val V38_RUNTIME_ACTUAL_TARGETS_RESOLVED = "KMPF-V38"
    const val V39_FLAVOR_SOURCE_SET = "KMPF-V39"
    const val V40_PER_TARGET_FLAVOR_SOURCE_SET = "KMPF-V40"
    const val V41_DEPENDSON_GRAPH = "KMPF-V41"
    const val V42_COMPOSE_RESOURCES_ROUTER = "KMPF-V42"
    const val V43_ANDROID_RES_SRCDIR = "KMPF-V43"
    const val V44_RESOURCE_FALLBACK_CHAIN = "KMPF-V44"
    const val V45_ANDROID_FIREBASE_CONFIG_PLACEMENT = "KMPF-V45"
    const val V46_IOS_FIREBASE_XCCONFIG_LINE = "KMPF-V46"
    const val V47_IOS_FIREBASE_COPY_SCRIPT_PRESENT = "KMPF-V47"
    const val V48_PBXPROJ_BASE_XCCONFIG_WIRED = "KMPF-V48"
    const val V49_INFO_PLIST_BUNDLE_ID_INTERP = "KMPF-V49"
    const val V50_VERSION_CODE_PROPAGATED = "KMPF-V50"
    const val V51_SIGNING_ENV_VAR_SET = "KMPF-V51"
    const val V52_WINDOWS_UPGRADE_UUID = "KMPF-V52"
    const val V53_LINUX_APP_CATEGORY = "KMPF-V53"

    val ALL: List<String> = listOf(
        V31_PURE_AGP_NO_KMP_WIRING, V32_PURE_AGP_NO_CODEGEN_CLAIM,
        V33_BUNDLE_ID_SUFFIX_FORMAT, V34_NO_BUNDLE_ID_SUFFIX_WARN,
        V35_COMPOSE_NO_INTEGRATOR, V36_WEB_NO_INTEGRATOR,
        V37_RUNTIME_EXPECT_AND_ACTUAL, V38_RUNTIME_ACTUAL_TARGETS_RESOLVED,
        V39_FLAVOR_SOURCE_SET, V40_PER_TARGET_FLAVOR_SOURCE_SET, V41_DEPENDSON_GRAPH,
        V42_COMPOSE_RESOURCES_ROUTER, V43_ANDROID_RES_SRCDIR, V44_RESOURCE_FALLBACK_CHAIN,
        V45_ANDROID_FIREBASE_CONFIG_PLACEMENT, V46_IOS_FIREBASE_XCCONFIG_LINE,
        V47_IOS_FIREBASE_COPY_SCRIPT_PRESENT,
        V48_PBXPROJ_BASE_XCCONFIG_WIRED, V49_INFO_PLIST_BUNDLE_ID_INTERP,
        V50_VERSION_CODE_PROPAGATED, V51_SIGNING_ENV_VAR_SET,
        V52_WINDOWS_UPGRADE_UUID, V53_LINUX_APP_CATEGORY,
    )
}
