/*
 * Copyright 2026 MobileByteLabs
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

package com.mobilebytelabs.kmpflavors.internal

import java.io.File

/**
 * Phase 2 — emits per-variant xcconfig files.
 * Output: build/generated/iosFlavorConfigs/{flavor}{BuildType}.xcconfig
 */
internal object IosXcconfigGenerator {
    fun generate(spec: IosXcconfigSpec, outDir: File): File {
        outDir.mkdirs()
        val file = outDir.resolve("${spec.variantName}.xcconfig")
        file.bufferedWriter().use { w ->
            w.appendLine("// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT")
            w.appendLine("PRODUCT_BUNDLE_IDENTIFIER = ${spec.bundleId}")
            spec.xcconfigVars.toSortedMap().forEach { (k, v) ->
                w.appendLine("$k = $v")
            }
            spec.googleServiceFile?.let {
                w.appendLine("KMPF_GOOGLE_SERVICE_FILE = $it")
            }
        }
        return file
    }
}
