/*
 * Copyright 2026 MobileByteLabs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.mobilebytelabs.kmpflavors.internal

import com.mobilebytelabs.kmpflavors.FlavorVariant
import com.mobilebytelabs.kmpflavors.KmpFlavorExtension
import org.gradle.api.Project
import org.gradle.api.tasks.bundling.Tar
import org.jetbrains.kotlin.gradle.plugin.KotlinTarget

/**
 * v2.2 Phase 5C — per-variant npm registry publishing (opt-in).
 *
 * v2.1 Phase 5B+5C documented npm registry publishing as "intentionally
 * consumer-side per the v2.1 plan risk register" — the plugin produces
 * classifier-tagged Maven publications; consumers wire `npm publish`
 * themselves against their `~/.npmrc` credentials.
 *
 * v2.2 Phase 5C lands plugin-side support as an **opt-in** behind
 * `kmpFlavors.npmPublishMatrix.set(true)`. When opted in, for each
 * (inactive variant × `js(IR)` / `wasmJs()` target):
 *   - Generates a per-variant `package.json` with
 *     `name = "{prefix}-{variant}"`. Prefix defaults to `rootProject.name`;
 *     override via `kmpFlavors.npmPackagePrefix.set("custom")`.
 *   - Registers a `{variant}KotlinNpmPackage` Tar task wrapping the variant
 *     compilation's JS output as an npm tarball (.tgz).
 *   - npm registry credentials remain in `~/.npmrc` — the plugin does not
 *     manage them. Consumers run `kotlinNpmPublishToRegistry` separately
 *     OR upload the tarball manually.
 *
 * No-op when:
 *   - `publishMatrix=false` (no per-variant publishing surface to attach to).
 *   - `npmPublishMatrix=false` (default; consumer hasn't opted in).
 *   - No `js(IR)` / `wasmJs()` target declared.
 *   - No inactive variants.
 */
internal object PerVariantNpmPublishConfigurator {

    fun configure(project: Project, extension: KmpFlavorExtension, inactiveVariants: List<FlavorVariant>, nonAndroidTargets: List<KotlinTarget>) {
        if (!extension.publishMatrix.getOrElse(false)) return
        if (!extension.npmPublishMatrix.getOrElse(false)) return
        if (inactiveVariants.isEmpty()) return

        val jsFamilyTargets = nonAndroidTargets.filter { target ->
            val platformType = target.platformType.name
            platformType == "js" || platformType == "wasm"
        }
        if (jsFamilyTargets.isEmpty()) return

        val packagePrefix = extension.npmPackagePrefix.getOrElse(project.rootProject.name)
        var registered = 0

        for (jsTarget in jsFamilyTargets) {
            val compilations = jsTarget.compilations
            for (variant in inactiveVariants) {
                val variantCompilation = compilations.findByName(variant.name) ?: continue
                val variantCap = variant.name.replaceFirstChar { it.uppercase() }
                val targetCap = jsTarget.name.replaceFirstChar { it.uppercase() }

                // package.json generator task.
                val packageJsonTaskName = "generate${variantCap}${targetCap}PackageJson"
                val packageName = "$packagePrefix-${variant.name}"
                val packageJsonDir = project.layout.buildDirectory.dir(
                    "kmpFlavors/npm/${variant.name}-${jsTarget.name}",
                )
                project.tasks.register(packageJsonTaskName) {
                    group = "kmpFlavors variants"
                    description = "Generates package.json for variant '${variant.name}' on " +
                        "JS-family target '${jsTarget.name}' (Phase 5C)."
                    val outDir = packageJsonDir
                    outputs.dir(outDir)
                    doLast {
                        val dir = outDir.get().asFile
                        dir.mkdirs()
                        val version = project.version.toString().ifBlank { "0.0.0-SNAPSHOT" }
                        val content = """{
                          "name": "$packageName",
                          "version": "$version",
                          "main": "kotlin/$packageName.js",
                          "description": "Per-variant npm package generated by kmp-product-flavors v2.2 Phase 5C. Variant: ${variant.name}. Target: ${jsTarget.name}.",
                          "license": "${project.findProperty("kmpFlavors.npm.license") ?: "Apache-2.0"}"
                        }
                        """.trimIndent()
                        java.io.File(dir, "package.json").writeText(content)
                        logger.lifecycle(
                            "[KMP Flavors] Phase 5C — wrote package.json for '${variant.name}' on " +
                                "target '${jsTarget.name}' (package=$packageName, version=$version).",
                        )
                    }
                }

                // Tarball task that bundles JS output + the generated package.json into a .tgz
                // resolvable by `npm install` from a local Verdaccio or pushed to a registry.
                val npmPackageTaskName = "${variant.name}KotlinNpmPackage$targetCap"
                project.tasks.register(npmPackageTaskName, Tar::class.java) {
                    group = "kmpFlavors variants"
                    description = "Bundles JS output + package.json for variant '${variant.name}' " +
                        "on target '${jsTarget.name}' as an npm tarball (.tgz)."
                    archiveBaseName.set(packageName)
                    archiveExtension.set("tgz")
                    compression = org.gradle.api.tasks.bundling.Compression.GZIP
                    archiveClassifier.set(jsTarget.name)
                    dependsOn(packageJsonTaskName)
                    from(variantCompilation.output.allOutputs)
                    from(packageJsonDir)
                    destinationDirectory.set(
                        project.layout.buildDirectory.dir("kmpFlavors/npm/$packageName"),
                    )
                }
                registered += 1
            }
        }

        project.logger.lifecycle(
            "[KMP Flavors] Phase 5C — registered $registered per-variant npm tarball task(s). " +
                "Bundles produced at `build/kmpFlavors/npm/$packagePrefix-{variant}/`. " +
                "Push to a registry via `npm publish` against your `~/.npmrc` credentials.",
        )
    }
}
