/*
 * Copyright 2026 MobileByteLabs
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

package com.mobilebytelabs.kmpflavors.internal

import java.io.File

/**
 * Phase 6 — emits KmpFlavorsRuntime expect + 5 actuals.
 * Files land at build/generated/kmpflavors-runtime/{sourceSet}/{pkgPath}/KmpFlavorsRuntime{.ext}.kt
 * Each actual reads from its platform-native source — NEVER hardcoded at codegen time.
 */
internal object RuntimeApiGenerator {

    /**
     * Emits a SINGLE concrete `object KmpFlavorsRuntime` into `commonMain` — no
     * `expect`/`actual`. A commonMain `expect` cannot reach a module's per-variant
     * compilations (`compileDevKotlinDesktop` etc.): the plugin replays the platform
     * `actual` srcDirs into each variant compilation's defaultSourceSet, but KGP's
     * source-set rules block the `expect` from following, leaving orphan `actual`s.
     * A concrete common object sidesteps that entirely and compiles on Android, iOS,
     * Web, Desktop AND every per-variant compilation. The flavor/build-type values are
     * resolved at codegen (constants); they are fixed for the built variant, so this is
     * equivalent to — and more robust than — the old platform-native runtime reads.
     */
    fun generate(spec: RuntimeApiSpec, hint: RuntimeVariantHint, outRoot: File): List<File> {
        outRoot.mkdirs()
        val pkgPath = spec.packageName.replace('.', '/')
        val dir = outRoot.resolve("commonMain").resolve(pkgPath)
        dir.mkdirs()
        val file = dir.resolve("KmpFlavorsRuntime.kt")
        file.writeText(RuntimeConcreteCommonTemplate.render(spec.packageName, hint))
        return listOf(file)
    }
}

internal object RuntimeConcreteCommonTemplate {
    /** Escape a value for embedding inside a Kotlin double-quoted string literal. */
    private fun esc(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")

    fun render(pkg: String, hint: RuntimeVariantHint): String = """
// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package $pkg

/** Build-variant info resolved at codegen (fixed for the built variant). */
public object KmpFlavorsRuntime {
    public val flavorName: String = ${'"'}${esc(hint.flavorName)}${'"'}
    public val buildTypeName: String = ${'"'}${esc(hint.buildTypeName)}${'"'}
    public val bundleId: String = ${'"'}${esc(hint.bundleId)}${'"'}
    public val applicationId: String = bundleId
    public val appDisplayName: String = ${'"'}${esc(hint.appDisplayName)}${'"'}
    public val appVersion: String = ${'"'}${esc(hint.appVersion)}${'"'}
    public val isDebug: Boolean = ${hint.isDebug}
    public val isDemo: Boolean = ${hint.isDemo}
    public fun get(key: String): String? = when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "applicationId" -> applicationId
        "appDisplayName" -> appDisplayName
        "appVersion" -> appVersion
        "isDebug" -> isDebug.toString()
        "isDemo" -> isDemo.toString()
        else -> null
    }
}
    """.trimIndent() + "\n"
}

internal object RuntimeExpectTemplate {
    fun render(pkg: String): String = """
// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package $pkg

public expect object KmpFlavorsRuntime {
    public val flavorName: String
    public val buildTypeName: String
    public val bundleId: String
    public val applicationId: String
    public val appDisplayName: String
    public val appVersion: String
    public val isDebug: Boolean
    public val isDemo: Boolean
    public fun get(key: String): String?
}
    """.trimIndent() + "\n"
}

internal object RuntimeAndroidActualTemplate {
    fun render(pkg: String): String = """
// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
// Uses reflection to read BuildConfig so this compiles in both
// `com.android.application` modules (full BuildConfig present) and
// `com.android.library` modules (sparse or no BuildConfig).
package $pkg

public actual object KmpFlavorsRuntime {
    private fun readStringField(className: String, fieldName: String): String? = try {
        Class.forName(className).getField(fieldName).get(null) as? String
    } catch (_: Throwable) { null }

    private fun readBooleanField(className: String, fieldName: String): Boolean? = try {
        val f = Class.forName(className).getField(fieldName)
        (f.get(null) as? Boolean)
    } catch (_: Throwable) { null }

    private val buildConfigClass: String = "$pkg.BuildConfig"

    public actual val flavorName: String =
        readStringField(buildConfigClass, "FLAVOR") ?: ""
    public actual val buildTypeName: String =
        readStringField(buildConfigClass, "BUILD_TYPE") ?: ""
    public actual val bundleId: String =
        readStringField(buildConfigClass, "APPLICATION_ID") ?: ""
    public actual val applicationId: String = bundleId
    public actual val appDisplayName: String = ""
    public actual val appVersion: String =
        readStringField(buildConfigClass, "VERSION_NAME") ?: ""
    public actual val isDebug: Boolean =
        readBooleanField(buildConfigClass, "DEBUG") ?: false
    public actual val isDemo: Boolean =
        readBooleanField(buildConfigClass, "IS_DEMO") ?: (flavorName == "demo")
    public actual fun get(key: String): String? = when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "applicationId" -> applicationId
        "appDisplayName" -> appDisplayName
        "appVersion" -> appVersion
        "isDebug" -> isDebug.toString()
        "isDemo" -> isDemo.toString()
        else -> null
    }
}
    """.trimIndent() + "\n"
}

internal object RuntimeIosActualTemplate {
    fun render(pkg: String): String = """
// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package $pkg

import platform.Foundation.NSBundle

public actual object KmpFlavorsRuntime {
    private val info: Map<Any?, *>? = NSBundle.mainBundle.infoDictionary
    public actual val flavorName: String = (info?.get("KMPFFlavorName") as? String) ?: ""
    public actual val buildTypeName: String = (info?.get("KMPFBuildTypeName") as? String) ?: ""
    public actual val bundleId: String = NSBundle.mainBundle.bundleIdentifier ?: ""
    public actual val applicationId: String = bundleId
    public actual val appDisplayName: String =
        (info?.get("CFBundleDisplayName") as? String) ?: (info?.get("CFBundleName") as? String) ?: ""
    public actual val appVersion: String = (info?.get("CFBundleShortVersionString") as? String) ?: ""
    public actual val isDebug: Boolean = (info?.get("KMPFIsDebug") as? String)?.equals("YES", ignoreCase = true) ?: false
    public actual val isDemo: Boolean =
        (info?.get("KMPFIsDemo") as? String)?.equals("YES", ignoreCase = true) ?: (flavorName == "demo")
    public actual fun get(key: String): String? = (info?.get("KMPF${'$'}key") as? String) ?: when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "appVersion" -> appVersion
        else -> null
    }
}
    """.trimIndent() + "\n"
}

internal object RuntimeDesktopActualTemplate {
    fun render(pkg: String): String = """
// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package $pkg

import java.util.jar.Manifest

public actual object KmpFlavorsRuntime {
    private val manifest: Manifest? = runCatching {
        KmpFlavorsRuntime::class.java.classLoader.getResources("META-INF/MANIFEST.MF").toList()
            .firstNotNullOfOrNull { url ->
                runCatching {
                    url.openStream().use {
                        Manifest(it).takeIf { m -> m.mainAttributes.getValue("KMPF-Flavor") != null }
                    }
                }.getOrNull()
            }
    }.getOrNull()
    private fun attr(key: String): String = manifest?.mainAttributes?.getValue(key) ?: ""

    public actual val flavorName: String = attr("KMPF-Flavor")
    public actual val buildTypeName: String = attr("KMPF-BuildType")
    public actual val bundleId: String = attr("KMPF-BundleId")
    public actual val applicationId: String = attr("KMPF-ApplicationId").ifEmpty { bundleId }
    public actual val appDisplayName: String = attr("KMPF-AppDisplayName")
    public actual val appVersion: String = attr("Implementation-Version").ifEmpty { attr("KMPF-AppVersion") }
    public actual val isDebug: Boolean = attr("KMPF-IsDebug").equals("true", ignoreCase = true)
    public actual val isDemo: Boolean = attr("KMPF-IsDemo").equals("true", ignoreCase = true) || flavorName == "demo"
    public actual fun get(key: String): String? = attr("KMPF-${'$'}key").takeIf { it.isNotEmpty() }
}
    """.trimIndent() + "\n"
}

internal object RuntimeJsActualTemplate {
    fun render(pkg: String): String = """
// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package $pkg

@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_FLAVOR_NAME__: String
@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_BUILD_TYPE_NAME__: String
@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_BUNDLE_ID__: String
@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_APP_DISPLAY_NAME__: String
@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_APP_VERSION__: String
@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_IS_DEBUG__: Boolean
@Suppress("ObjectPropertyName", "ClassName", "FunctionName")
private external val __KMPF_IS_DEMO__: Boolean

public actual object KmpFlavorsRuntime {
    public actual val flavorName: String = __KMPF_FLAVOR_NAME__
    public actual val buildTypeName: String = __KMPF_BUILD_TYPE_NAME__
    public actual val bundleId: String = __KMPF_BUNDLE_ID__
    public actual val applicationId: String = bundleId
    public actual val appDisplayName: String = __KMPF_APP_DISPLAY_NAME__
    public actual val appVersion: String = __KMPF_APP_VERSION__
    public actual val isDebug: Boolean = __KMPF_IS_DEBUG__
    public actual val isDemo: Boolean = __KMPF_IS_DEMO__
    public actual fun get(key: String): String? = when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "appVersion" -> appVersion
        else -> null
    }
}
    """.trimIndent() + "\n"
}

internal object RuntimeWasmJsActualTemplate {
    fun render(pkg: String): String = RuntimeJsActualTemplate.render(pkg)
}
