/*
 * Copyright 2026 MobileByteLabs
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

package com.mobilebytelabs.kmpflavors.internal

import com.mobilebytelabs.kmpflavors.KmpFlavorExtension
import org.gradle.api.Project
import org.gradle.api.logging.Logger
import java.io.File

/**
 * Phase 5 — Writes per-flavor webpack overlay configs to <module>-webpack.config.d/.
 * Also injects __KMPF_*__ DefinePlugin constants used by Phase 6 jsMain/wasmJsMain actuals.
 */
internal object WebFlavorIntegrator {

    fun apply(project: Project, ext: KmpFlavorExtension, logger: Logger): Int {
        val flavors = ext.flavors.toList()
        val buildTypes = ext.buildTypes.toList().ifEmpty { return 0 }
        val module = project.name
        val iconDir = project.projectDir.resolve("branding/icons/web")
        val appDisplayName = project.rootProject.name

        // Resolve a default bundleId base — use applicationId or fallback to package
        val bundleIdBase = project.findProperty("applicationId") as? String
            ?: project.name

        var count = 0
        for (targetType in listOf("js", "wasm")) {
            val overlayDir = project.layout.buildDirectory
                .dir("$targetType/packages/$module-webpack.config.d").get().asFile
            for (flavor in flavors) for (buildType in buildTypes) {
                val spec = WebFlavorSpec.from(flavor, buildType, appDisplayName, bundleIdBase, iconDir)
                writeOverlay(overlayDir, spec, logger)
                count++
            }
        }
        logger.lifecycle("[KMP Flavors] WebFlavorIntegrator wrote $count overlay files")
        return count
    }

    fun writeOverlay(overlayDir: File, spec: WebFlavorSpec, logger: Logger): File {
        overlayDir.mkdirs()
        val file = overlayDir.resolve("kmp-flavors-${spec.variantName}.js")
        file.writeText(renderOverlay(spec))
        logger.info("[KMP Flavors] wrote overlay ${file.name}")
        return file
    }

    fun renderOverlay(spec: WebFlavorSpec): String = buildString {
        appendLine("// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT")
        appendLine("const HtmlWebpackPlugin = require('html-webpack-plugin');")
        appendLine("const webpack = require('webpack');")
        appendLine("const path = require('path');")
        appendLine("config.plugins = (config.plugins || []).filter(p => !(p instanceof HtmlWebpackPlugin));")
        appendLine("config.plugins.push(new HtmlWebpackPlugin({")
        appendLine("    template: path.resolve(__dirname, '../../../../src/jsMain/resources/index.html.template'),")
        appendLine("    templateParameters: {")
        appendLine("        KMPF_TITLE: ${quote(spec.title)},")
        spec.favicon?.let { appendLine("        KMPF_FAVICON: ${quote(it.name)},") }
        spec.themeColor?.let { appendLine("        KMPF_THEME_COLOR: ${quote(it)},") }
        appendLine("    },")
        appendLine("}));")
        appendLine("// Phase 6 runtime API — DefinePlugin constants read by jsMain/wasmJsMain actuals")
        appendLine("config.plugins.push(new webpack.DefinePlugin({")
        appendLine("    '__KMPF_FLAVOR_NAME__': ${quote(spec.flavorName)},")
        appendLine("    '__KMPF_BUILD_TYPE_NAME__': ${quote(spec.buildTypeName)},")
        appendLine("    '__KMPF_BUNDLE_ID__': ${quote(spec.bundleId)},")
        appendLine("    '__KMPF_APP_DISPLAY_NAME__': ${quote(spec.appDisplayName)},")
        appendLine("    '__KMPF_APP_VERSION__': ${quote("1.0.0")},")
        appendLine("    '__KMPF_IS_DEBUG__': ${spec.isDebug},")
        appendLine("    '__KMPF_IS_DEMO__': ${spec.isDemo},")
        appendLine("}));")
        appendLine("config.output = config.output || {};")
        appendLine("config.output.path = path.resolve(config.output.path, '../${spec.outputDir}');")
    }

    private fun quote(s: String) = "'${s.replace("'", "\\'")}'"
}
