/*
 * Copyright 2026 MobileByteLabs
 * Licensed under the Apache License, Version 2.0 (the "License");
 */

package com.mobilebytelabs.kmpflavors.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Phase 3 — writes the umbrella iOSApp.xcconfig that #includes the per-variant xcconfigs (Phase 2 output).
 */
@CacheableTask
abstract class KmpFlavorsXcodeIntegrateTask : DefaultTask() {
    @get:Input
    abstract val xcconfigGeneratedDir: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        group = "kmp flavors"
        description = "Writes umbrella iOSApp.xcconfig referencing the per-variant xcconfig files."
    }

    @TaskAction
    fun run() {
        val out = outputDir.get().asFile
        out.mkdirs()
        val umbrella = out.resolve("iOSApp.xcconfig")
        val relativeInclude = xcconfigGeneratedDir.get()
        umbrella.writeText(
            """
            |// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
            |#include "$relativeInclude/${'$'}(CONFIGURATION).xcconfig"
            |
            """.trimMargin(),
        )
        logger.lifecycle("[KMP Flavors] wrote umbrella ${umbrella.relativeTo(project.projectDir)}")
    }
}
