// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package com.example.snapshot

import platform.Foundation.NSBundle

public actual object KmpFlavorsRuntime {
    private val info: Map<Any?, *>? = NSBundle.mainBundle.infoDictionary
    public actual val flavorName: String = (info?.get("KMPFFlavorName") as? String) ?: ""
    public actual val buildTypeName: String = (info?.get("KMPFBuildTypeName") as? String) ?: ""
    public actual val bundleId: String = NSBundle.mainBundle.bundleIdentifier ?: ""
    public actual val applicationId: String = bundleId
    public actual val appDisplayName: String =
        (info?.get("CFBundleDisplayName") as? String) ?: (info?.get("CFBundleName") as? String) ?: ""
    public actual val appVersion: String = (info?.get("CFBundleShortVersionString") as? String) ?: ""
    public actual val isDebug: Boolean = (info?.get("KMPFIsDebug") as? String)?.equals("YES", ignoreCase = true) ?: false
    public actual val isDemo: Boolean =
        (info?.get("KMPFIsDemo") as? String)?.equals("YES", ignoreCase = true) ?: (flavorName == "demo")
    public actual fun get(key: String): String? = (info?.get("KMPF$key") as? String) ?: when (key) {
        "flavorName" -> flavorName
        "buildTypeName" -> buildTypeName
        "bundleId" -> bundleId
        "appVersion" -> appVersion
        else -> null
    }
}
