// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package com.example.snapshot

import java.util.jar.Manifest

public actual object KmpFlavorsRuntime {
    private val manifest: Manifest? = runCatching {
        KmpFlavorsRuntime::class.java.classLoader.getResources("META-INF/MANIFEST.MF").toList()
            .firstNotNullOfOrNull { url ->
                runCatching {
                    url.openStream().use {
                        Manifest(it).takeIf { m -> m.mainAttributes.getValue("KMPF-Flavor") != null }
                    }
                }.getOrNull()
            }
    }.getOrNull()
    private fun attr(key: String): String = manifest?.mainAttributes?.getValue(key) ?: ""

    public actual val flavorName: String = attr("KMPF-Flavor")
    public actual val buildTypeName: String = attr("KMPF-BuildType")
    public actual val bundleId: String = attr("KMPF-BundleId")
    public actual val applicationId: String = attr("KMPF-ApplicationId").ifEmpty { bundleId }
    public actual val appDisplayName: String = attr("KMPF-AppDisplayName")
    public actual val appVersion: String = attr("Implementation-Version").ifEmpty { attr("KMPF-AppVersion") }
    public actual val isDebug: Boolean = attr("KMPF-IsDebug").equals("true", ignoreCase = true)
    public actual val isDemo: Boolean = attr("KMPF-IsDemo").equals("true", ignoreCase = true) || flavorName == "demo"
    public actual fun get(key: String): String? = attr("KMPF-$key").takeIf { it.isNotEmpty() }
}
