// Generated by com.mobilebytelabs.kmp-product-flavors — DO NOT EDIT
package com.example.snapshot

public expect object KmpFlavorsRuntime {
    public val flavorName: String
    public val buildTypeName: String
    public val bundleId: String
    public val applicationId: String
    public val appDisplayName: String
    public val appVersion: String
    public val isDebug: Boolean
    public val isDemo: Boolean
    public fun get(key: String): String?
}
